### ISSUE TITLE
Add support for unicode characters (like äöü etc) in the ...InFile.py files

### ISSUE THREAD

**Issue by emilmerle** [emilmerle/FindingThingsWithPython#2] opened 2020-09-09 14:22 UTC
Reading unicode characters like the german ä, ö and ü does not work in all ...InFile.py files.

**Comment by rexdivakar** [comment] 2020-09-26 07:44
Can u please provide a sample text file for validating my scripts ?

**Comment by rexdivakar** [comment] 2020-09-26 08:48
Solved the issue, please let me know how to contact u for collaboration

**Comment by emilmerle** [comment] 2020-09-26 15:52
Sample text for an alliteration with Unicode characters would be something like: "Ich mag wütende Wachen nicht", where the alliteration "wütende Wachen" should be found.  
If you solved the issue you can open a pull request. But for that you need to fork the repo so please look for a tutorial how to open a pull request.

**Comment by rexdivakar** [comment] 2020-09-26 15:58
Hey @emilmerle  i have completed it but i'm waiting since i wish to add this PR for my Hacktoberfest contribution

**Comment by rexdivakar** [comment] 2020-10-03 13:53
hey @emilmerle  can u pls close the issue ??

**Comment by emilmerle** [comment] 2020-10-03 18:30
As far as I know it is not fixed yet. In the Email files it does not work correctly yet.

**Comment by rexdivakar** [comment] 2020-10-04 00:35
When i tested it, It had no issues but anyways can u pls share me a sample error ? @emilmerle

**Comment by emilmerle** [comment] 2020-10-04 12:11
There is no error message but email addresses like "höhe@gmail.com" are not found correctly. Here only "he@gmail.com" is found, although its not the full email address.

**Comment by rexdivakar** [comment] 2020-10-04 12:13
will update a fix soon @emilmerle

**Comment by rexdivakar** [comment] 2020-10-06 11:38
When i run the code, im getting "he@gmail.com" for "höhe@gmail.com"
Is this the right thing or what should i get pls update !

**Comment by emilmerle** [comment] 2020-10-06 11:54
No this is not the right output of the example.
An input like "höhe@gmail.com" should output "höhe@gmail.com" 
or the input "example@müller.com" should output "example@müller.com". 
This is not the case right now.

**Comment by rexdivakar** [comment] 2020-10-06 11:58
Oh k got it will fix it

**Comment by rexdivakar** [comment] 2020-10-06 12:02
I havn't fixed it may i know why u closing it ? @emilmerle

**Closed** 2020-10-06 12:01 UTC
Labels: bug, enhancement, good first issue, hacktoberfest, help wanted

**Comment by rexdivakar** [comment] 2020-10-06 12:23
I have fixed the issue, If u open it i will update my changes !!

**Comment by rexdivakar** [comment] 2020-10-07 02:30
Thanks for closing the issue abruptly without even notifying the cause and wasting my tim e😤😤😤
